# Generated by Django 5.1.1 on 2024-11-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=69)),
                ('item_type', models.CharField(max_length=69)),
                ('cost', models.FloatField()),
            ],
        ),
    ]
