# Generated by Django 5.1.3 on 2024-11-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=100)),
                ('game_type', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('hero_id', models.AutoField(primary_key=True, serialize=False)),
                ('hero_name', models.CharField(max_length=69)),
                ('role', models.CharField(max_length=12)),
            ],
        ),
    ]
