# Generated by Django 5.1.3 on 2024-11-28 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackersystem', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
