# Generated by Django 5.1.3 on 2024-11-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('hero_id', models.AutoField(primary_key=True, serialize=False)),
                ('hero_name', models.CharField(max_length=69)),
                ('role', models.CharField(max_length=69)),
                ('match', models.CharField(max_length=69)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
