# Generated by Django 5.1.3 on 2024-11-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('analytics_id', models.AutoField(primary_key=True, serialize=False)),
                ('kills', models.IntegerField()),
                ('death', models.IntegerField()),
                ('assist', models.IntegerField()),
                ('win_loss', models.CharField(max_length=10)),
            ],
        ),
    ]
